version: '3'
services:
  db:
    image: postgres:9.4
    # ports:
    #   - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    # network_mode: "host"
  web:
    build: .
    command: bundle exec rails server -b "0.0.0.0"
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      # - DB_HOST=db
      # - USERNAME=postgres
      - DB_HOST=host.docker.internal
      - USERNAME=baldor
      - PASSWORD=baldor123
    tty: true
    stdin_open: true
